TechMed/Areas/Admin/Models/Recruitment/RecruitmentCate.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TechMed.Areas.Admin.Models.Recruitment
{
    [Table("RecruitmentCate")]
    public class RecruitmentCate
    {
        [Key]
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Name must be between 3 and 100 characters")]
        public string Name { get; set; } = "";

        public List<Recruitment>? Recruitments { get; set; }
    }
}

TechMed/Areas/Admin/Controllers/RecruitmentCatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TechMed.Areas.Admin.Data;
using TechMed.Areas.Admin.Models.News;
using TechMed.Areas.Admin.Models.Recruitment;
using X.PagedList;

namespace TechMed.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class RecruitmentCatesController : Controller
    {
        private readonly AppDbContext _context;

        public RecruitmentCatesController(AppDbContext context)
        {
            _context = context;
        }

		// GET: Admin/RecruitmentCates
		public async Task<IActionResult> Index(int? page)
		{
			int pageSize = 10; //SL phan tu tren 1 trang
			int pageNumber = (page ?? 1);
			if (_context.RecruitmentCate == null)
			{
				return Problem("Entity set 'AppDbContext.Banner' is null.");
			}
			var recruitmentCates = await _context.RecruitmentCate.ToListAsync();
			IPagedList<RecruitmentCate> recruitmentCatesPaging = recruitmentCates.ToPagedList(pageNumber, pageSize);
			if (recruitmentCates != null)
			{
				return View(recruitmentCatesPaging);
			}
			else
			{
				return Problem("Entity set 'AppDbContext.Banner' is null.");
			}
		}


		[HttpPost]
		public async Task<IActionResult> Index(string? keyword, int? page)
		{
			int pageSize = 10; //SL phan tu tren 1 trang
			int pageNumber = (page ?? 1);
			if (_context.RecruitmentCate == null)
			{
				return Problem("Entity set 'AppDbContext.Banner' is null.");
			}
			IQueryable<RecruitmentCate> recruitmentCatesQuerry = _context.RecruitmentCate;

			if (!string.IsNullOrEmpty(keyword))
			{
				recruitmentCatesQuerry = recruitmentCatesQuerry.Where(n => n.Name.Contains(keyword));
			}
			var recruitmentCates = await recruitmentCatesQuerry.ToListAsync();

			IPagedList<RecruitmentCate> recruitmentCatesPaging = recruitmentCates.ToPagedList(pageNumber, pageSize);
			ViewBag.keyword = keyword;
			if (recruitmentCates != null)
			{
				return View(recruitmentCatesPaging);
			}
			else
			{
				return Problem("Entity set 'AppDbContext.Banner' is null.");
			}
		}

		// GET: Admin/RecruitmentCates/Details/5
		public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.RecruitmentCate == null)
            {
                return NotFound();
            }

            var recruitmentCate = await _context.RecruitmentCate
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recruitmentCate == null)
            {
                return NotFound();
            }

            return View(recruitmentCate);
        }

        // GET: Admin/RecruitmentCates/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/RecruitmentCates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] RecruitmentCate recruitmentCate)
        {
            if (ModelState.IsValid)
            {
                recruitmentCate.Id = Guid.NewGuid();
                _context.Add(recruitmentCate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(recruitmentCate);
        }

        // GET: Admin/RecruitmentCates/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.RecruitmentCate == null)
            {
                return NotFound();
            }

            var recruitmentCate = await _context.RecruitmentCate.FindAsync(id);
            if (recruitmentCate == null)
            {
                return NotFound();
            }
            return View(recruitmentCate);
        }

        // POST: Admin/RecruitmentCates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name")] RecruitmentCate recruitmentCate)
        {
            if (id != recruitmentCate.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(recruitmentCate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecruitmentCateExists(recruitmentCate.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(recruitmentCate);
        }

        // GET: Admin/RecruitmentCates/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.RecruitmentCate == null)
            {
                return NotFound();
            }

            var recruitmentCate = await _context.RecruitmentCate
                .FirstOrDefaultAsync(m => m.Id == id);
            if (recruitmentCate == null)
            {
                return NotFound();
            }

            return View(recruitmentCate);
        }

        // POST: Admin/RecruitmentCates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.RecruitmentCate == null)
            {
                return Problem("Entity set 'AppDbContext.RecruitmentCate'  is null.");
            }
            var recruitmentCate = await _context.RecruitmentCate.FindAsync(id);
            if (recruitmentCate != null)
            {
                _context.RecruitmentCate.Remove(recruitmentCate);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RecruitmentCateExists(Guid id)
        {
          return (_context.RecruitmentCate?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

TechMed/Areas/Admin/Views/RecruitmentCates/Create.cshtml
@model TechMed.Areas.Admin.Models.Recruitment.RecruitmentCate

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Tạo mới danh mục tuyển dụng</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TechMed/Areas/Admin/Views/RecruitmentCates/Delete.cshtml
@model TechMed.Areas.Admin.Models.Recruitment.RecruitmentCate

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RecruitmentCate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TechMed/Areas/Admin/Views/RecruitmentCates/Details.cshtml
@model TechMed.Areas.Admin.Models.Recruitment.RecruitmentCate

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>RecruitmentCate</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TechMed/Areas/Admin/Views/RecruitmentCates/Edit.cshtml
@model TechMed.Areas.Admin.Models.Recruitment.RecruitmentCate

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>RecruitmentCate</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

TechMed/Areas/Admin/Views/RecruitmentCates/Index.cshtml
@model X.PagedList.IPagedList<TechMed.Areas.Admin.Models.Recruitment.RecruitmentCate>
@using X.PagedList.Mvc.Core
@{
	ViewData["Title"] = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Danh mục tuyển dụng</h1>

<div class="searchInner">
	<form method="post">
		<div class="row">
			<div class="searchField col-md-4 col-6">
				<input class="form-control" type="text" name="keyword" value="@ViewBag.keyword" placeholder="Search content here..." />
			</div>

			<div class="btnFilter col-md col-12">
				<input type="submit" value="Tìm kiếm" class="btn" />
			</div>
		</div>
	</form>
</div>

<div class="d-flex justify-content-between align-items-center button-header">
	<a class="btn btn-success btnCreateNew" asp-action="Create">Tạo mới</a>
	@Html.PagedListPager(Model, page => Url.Action("Index", "RecruitmentCates", new { page = page }))
</div>

<table class="table">
	<thead>
		<tr>
			<th>
				Tên
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					<div class="dropdown">
						<a class="dropdown-toggle" href="#" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
							<i class="fa-solid fa-bars text-secondary"></i>
						</a>

						<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
							<li><a class="dropdown-item" asp-action="Edit" asp-route-id="@item.Id"><i class="fa-solid fa-pencil"></i> Sửa</a></li>
							<li data-bs-toggle="modal" data-bs-target="#deleteModal" data-id="@item.Id" class="btnDelete">
								<a href="javascript:void(0)" class="dropdown-item"><i class="fa-solid fa-trash-can text-danger"></i> Xóa</a>
							</li>
						</ul>
					</div>
				</td>
			</tr>
		}
	</tbody>
</table>
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Xác nhận xóa ?</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="alert alert-warning" role="alert">
					Bạn có chắc chắn muốn xóa: Danh mục tuyển dụng
				</div>
			</div>
			<div class="modal-footer">
				<form asp-action="Delete">
					<input type="hidden" name="Id" class="idElement" />
					<input type="submit" value="Xóa" class="btn btn-danger" />
					<input type="button" value="không" class="btn btn-secondary" data-bs-dismiss="modal" />
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).on("click", ".btnDelete", function () {
		var itemId = $(this).data('id');
		$(".modal-footer .idElement").val(itemId);
	});
</script>