TechMed/Areas/Admin/Models/Recruitment/Recruitment.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TechMed.Areas.Admin.Models.Recruitment
{
    [Table("Recruitment")]
    public class Recruitment
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Tên công việc là bắt buộc")]
        public string Name { get; set; } = "";

        [StringLength(50, ErrorMessage = "Độ dài không quá 50 kí tự")]
        public string? Salary { get; set; }

        [StringLength(500, ErrorMessage = "Description must not be over 500 characters")]
        public string? Description { get; set; }
        [Required(ErrorMessage = "Nội dung bắt buộc")]
        public string Content { get; set; } = "";

        [DataType(DataType.Date)]
        public DateTime Deadline { get; set; }

        [StringLength(50, ErrorMessage = "Số lượng không quá 50 kí tự")]
        public string? Quantity { get; set; }
        public string? Image { get; set; }
		
		public DateTime CreatedDate { get; set; }

        [Required(ErrorMessage = "Start Date is required")]
		
		public DateTime StartDate { get; set; }
		
		public DateTime? EndDate { get; set; }

        public int Status { get; set; }

		public int? Order { get; set; }
		public int? Type { get; set; }
		public Guid? RecruitmentCateId { get; set; }
        public RecruitmentCate? RecruitmentCate { get; set; }

        public ICollection<RecruitmentTag>? RecruitmentTags { get; set; }

    }
}

TechMed/Areas/Admin/Models/Recruitment/RecruitmentCate.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TechMed.Areas.Admin.Models.Recruitment
{
    [Table("RecruitmentCate")]
    public class RecruitmentCate
    {
        [Key]
        public Guid Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Name must be between 3 and 100 characters")]
        public string Name { get; set; } = "";

        public List<Recruitment>? Recruitments { get; set; }
    }
}

TechMed/Areas/Admin/Models/Recruitment/RecruitmentTag.cs
using System.ComponentModel.DataAnnotations;

namespace TechMed.Areas.Admin.Models.Recruitment
{
    public class RecruitmentTag
    {
        public Recruitment Recruitment { get; set; }

        public Guid RecruitmentId { get; set;}

        public Tag Tag { get; set; }

        public Guid TagId { get; set; }
    }
}

TechMed/Areas/Admin/Models/Recruitment/Tag.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TechMed.Areas.Admin.Models.Recruitment
{
    [Table("Tag")]
    public class Tag
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Name must be between 3 and 100 characters")]
        public string Name { get; set; } = "";

        public ICollection<RecruitmentTag>? RecruitmentTags { get; set; }
    }
}

TechMed/Areas/Admin/Controllers/RecruitmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Reflection;
using TechMed.Areas.Admin.Data;
using TechMed.Areas.Admin.Models.Banner;
using TechMed.Areas.Admin.Models.News;
using TechMed.Areas.Admin.Models.Recruitment;
using X.PagedList;


namespace TechMed.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class RecruitmentController : Controller
    {
        private readonly AppDbContext _context;

        public RecruitmentController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Recruitment
        public async Task<IActionResult> Index(int? page)
        {
            if (_context.Recruitments != null)
            {
                int pageSize = 10; //SL phan tu tren 1 trang
                int pageNumber = (page ?? 1);
                var recruitments = await _context.Recruitments
                            .Include(r => r.RecruitmentCate) // Load thông tin của danh mục
                            .Include(r => r.RecruitmentTags) // Load thông tin của các tag
                                .ThenInclude(rt => rt.Tag) // Load thông tin của tag từ RecruitmentTag
								.OrderByDescending(n => n.CreatedDate)
							.ToListAsync();
                IPagedList<Recruitment> recruitmentsPaging = recruitments.ToPagedList(pageNumber, pageSize);
                if (recruitments != null)
                {
                    return View(recruitmentsPaging);
                }
                else
                {
                    return View();
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string? keyword, int? page)
        {
            if (_context.Recruitments != null)
            {
                int pageSize = 10; //SL phan tu tren 1 trang
                int pageNumber = (page ?? 1);
                IQueryable<Recruitment> recruitmentQuery = _context.Recruitments.Include(r => r.RecruitmentCate)
                    .Include(r => r.RecruitmentTags).ThenInclude(rt => rt.Tag).OrderByDescending(n => n.CreatedDate);

                if (!string.IsNullOrEmpty(keyword))
                {
                    recruitmentQuery = recruitmentQuery.Where(n => n.Name.Contains(keyword));
                }
                var recruitments = await recruitmentQuery.ToListAsync();
                IPagedList<Recruitment> recruitmentsPaging = recruitments.ToPagedList(pageNumber, pageSize);

                ViewBag.keyword = keyword;

                if (recruitments != null)
                {
                    return View(recruitmentsPaging);
                }
                else
                {
                    return View();
                }
            }
            return View();
        }

        // GET: Recruitment/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (_context.Recruitments != null)
            {
                var recruitment = await _context.Recruitments
                .Include(r => r.RecruitmentCate)
                .Include(r => r.RecruitmentTags).ThenInclude(r => r.Tag)
                .FirstOrDefaultAsync(m => m.Id == id);
                if (recruitment == null)
                {
                    return NotFound();
                }

                return View(recruitment);
            }
            return View();
        }

        // GET: Recruitment/Create
        public IActionResult Create()
        {
            ViewBag.Tags = new MultiSelectList(_context.Tags, "Id", "Name");
            ViewBag.RecruitmentCates = new SelectList(_context.RecruitmentCate, "Id", "Name");
            return View();
        }

        // POST: Recruitment/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Recruitment recruitment, List<Guid> RecruitmentTags, IFormFile? Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.Length > 0)
                {
                    // Tạo tên tệp ảnh duy nhất
                    var uniqueFileName = Guid.NewGuid().ToString() + "_" + Image.FileName;
                    // Lưu ảnh vào thư mục của ứng dụng
                    var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Upload/Recruitment", uniqueFileName);
                    using (var stream = new FileStream(imagePath, FileMode.Create))
                    {
                        await Image.CopyToAsync(stream);
                    }

                    recruitment.Image = Url.Content(Path.Combine("~/Upload/Recruitment/", uniqueFileName));
                }
                recruitment.Id = Guid.NewGuid();

                if (RecruitmentTags != null && RecruitmentTags.Count > 0)
                {
                    recruitment.RecruitmentTags = RecruitmentTags.Select(tagId => new RecruitmentTag { RecruitmentId = recruitment.Id, TagId = tagId }).ToList();
                }

                _context.Add(recruitment);

                // Lưu danh sách RecruitmentTag vào cơ sở dữ liệu
                if (recruitment.RecruitmentTags != null && recruitment.RecruitmentTags.Count > 0)
                {
                    foreach (var recruitmentTag in recruitment.RecruitmentTags)
                    {
                        _context.Add(recruitmentTag);
                    }
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Nếu ModelState.IsValid trả về false, quay lại trang tạo mới và hiển thị lại form với dữ liệu đã nhập
            ViewBag.Tags = new MultiSelectList(_context.Tags, "Id", "Name", RecruitmentTags);
            ViewBag.RecruitmentCates = new SelectList(_context.RecruitmentCate, "Id", "Name", recruitment.RecruitmentCateId);
            return View(recruitment);
        }

        // GET: Recruitment/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (_context.Recruitments != null)
            {
                var recruitment = await _context.Recruitments.Include(r => r.RecruitmentTags).FirstOrDefaultAsync(r => r.Id == id);
                if (recruitment == null)
                {
                    return NotFound();
                }
                ViewBag.Tags = new MultiSelectList(_context.Tags, "Id", "Name", selectedValues: recruitment.RecruitmentTags.Select(rt => rt.TagId));
                ViewBag.RecruitmentCates = new SelectList(_context.RecruitmentCate, "Id", "Name", recruitment.RecruitmentCateId);
                return View(recruitment);
            }
            return View();
        }

        // POST: Recruitment/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Recruitment recruitment, List<Guid> Tags, IFormFile? Image, string? imgData)
        {
            if (id != recruitment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (Image != null && Image.Length > 0)
                    {
                        if (imgData != null)
                        {
                            DeleteImage(imgData);
                        }
                        // Tạo tên tệp ảnh duy nhất
                        var uniqueFileName = Guid.NewGuid().ToString() + "_" + Image.FileName;
                        // Lưu ảnh vào thư mục của ứng dụng
                        var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Upload/Recruitment", uniqueFileName);
                        using (var stream = new FileStream(imagePath, FileMode.Create))
                        {
                            await Image.CopyToAsync(stream);
                        }

                        recruitment.Image = Url.Content(Path.Combine("~/Upload/Recruitment/", uniqueFileName));
                    }
                    else
                    {
                        recruitment.Image = imgData;

                    }
                    // Xóa tất cả RecruitmentTag cũ liên quan đến recruitment.Id
                    var existingTags = _context.RecruitmentTags.Where(rt => rt.RecruitmentId == recruitment.Id);
                    _context.RecruitmentTags.RemoveRange(existingTags);

                    if (Tags != null && Tags.Count > 0)
                    {
                        recruitment.RecruitmentTags = Tags.Select(tagId => new RecruitmentTag { RecruitmentId = recruitment.Id, TagId = tagId }).ToList();
                    }

                    // Lưu danh sách RecruitmentTag vào cơ sở dữ liệu
                    if (recruitment.RecruitmentTags != null && recruitment.RecruitmentTags.Count > 0)
                    {
                        foreach (var recruitmentTag in recruitment.RecruitmentTags)
                        {
                            // Thêm mới recruitmentTag vào DbContext
                            _context.Add(recruitmentTag);
                        }
                    }
                    _context.Update(recruitment);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecruitmentExists(recruitment.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }

TechMed/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TechMed.Areas.Admin.Data;
using TechMed.Areas.Admin.Models.Banner;
using TechMed.Areas.Admin.Models.News;
using X.PagedList;

namespace TechMed.Controllers
{
    public class NewsController : Controller
    {
        private readonly AppDbContext _context;

        public NewsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: News
        public async Task<IActionResult> Index(int? page)
        {
            if(_context.News != null)
            {
                int pageSize = 5; //SL phan tu tren 1 trang
                int pageNumber = (page ?? 1);
                var news = await _context.News
                  .Include(n => n.NewsCategory)
				  .OrderByDescending(n => n.CreatedDate)
				  .ToListAsync();
                IPagedList<News> newsPaging = news.ToPagedList(pageNumber, pageSize);

                if (news != null)
                {
                    return View(newsPaging);
                }
                else
                {
                    return Problem("Entity set 'AppDbContext.News' is null.");
                }
            }
            return View();
        }

        // GET: News/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.News == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .Include(n => n.NewsCategory)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        
    }
}

TechMed/Controllers/RecruitmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using TechMed.Areas.Admin.Data;
using TechMed.Areas.Admin.Models.Recruitment;
using X.PagedList;

namespace TechMed.Controllers
{
    public class RecruitmentsController : Controller
    {
        private readonly AppDbContext _context;

        public RecruitmentsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Recruitments
        public async Task<IActionResult> Index(int? page)
        {
            if (_context.Recruitments != null)
            {
                int pageSize = 4; //SL phan tu tren 1 trang
                int pageNumber = (page ?? 1);
                var recruitments = await _context.Recruitments
                            .Include(r => r.RecruitmentCate).ToListAsync();
                IPagedList<Recruitment> recruitmentsPaging = recruitments.ToPagedList(pageNumber, pageSize);
                if (recruitments != null)
                {
                    return View(recruitmentsPaging);
                }
                else
                {
                    return View();
                }
            }
            return View();
        }

        // GET: Recruitments/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (_context.Recruitments != null)
            {
                var recruitment = await _context.Recruitments
                .Include(r => r.RecruitmentCate)
                .Include(r => r.RecruitmentTags).ThenInclude(r => r.Tag)
                .FirstOrDefaultAsync(m => m.Id == id);
                if (recruitment == null)
                {
                    return NotFound();
                }
                return View(recruitment);
            }
            return View();
        }

    }
}

TechMed/Views/Recruitments/Index.cshtml
@model X.PagedList.IPagedList<TechMed.Areas.Admin.Models.Recruitment.Recruitment>
@inject TechMed.Service.NewsService NewsService;
@inject TechMed.Service.RecruitmentService RecruitmentService;
@inject TechMed.Service.BannerService BannerService;
@using X.PagedList.Mvc.Core
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
	var bannerRecruitment = BannerService.GetBannerByPositionCode("BANNER_SECTION5");
	var enviromentNews = NewsService.GetNewsTypeNew(3);
	var hotRecruitment = RecruitmentService.GetHotRecruitments(4);
}
<link href="~/assests/css/blog.css" rel="stylesheet" />
<section class="blogpage">
	@if (BannerService != null)
	{
		@if (bannerRecruitment != null)
		{
			<div class="banner_career">
				@foreach (var banner in bannerRecruitment)
				{
					<img src="@banner.ImageUrl"
						 alt="@banner.Name">
				}
				<div class="container ">
					<div class="content">
						<div class="title">
						</div>
						<div class="description">
						</div>
					</div>
				</div>
			</div>
		}
	}
	
	<div class="containers" itemscope itemtype="https://schema.org/Blog">
		<meta itemprop="name" content="Tuyển dụng">
		<meta itemprop="description" content="">
		<div class="wrap_background_aside margin-bottom-0">
			<div class="section full_background_blog">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<section class="list-blogs blog-main listmain_blog">
								<table class="table-fill table">
									<thead>
										<tr>
											<th class="sh-name ">Vị trí tuyển dụng</th>
											<th class="sh-total">Lương</th>
											<th class="sh-size">Hạn nộp</th>
											<th class="sh-download"></th>
										</tr>
									</thead>
									<tbody class="table-hover">
										@foreach (var item in Model)
										{
											<tr>
												<td class="text-left sh-jobname">
													<a asp-action="Details" asp-route-id="@item.Id" title="@item.Name">@item.Name</a>
													<div class="time_user">
														<p class="time">
															<i class="far fa-clock"></i>
															#@if (item.RecruitmentCate != null)
															{
																@Html.DisplayFor(modelItem => item.RecruitmentCate.Name)
															}
														</p>
														<p class="user">
															<i class="fas fa-user"></i>
															#@item.Quantity
														</p>
													</div>
												</td>
												<td class="sh-group text-left">#@item.Salary</td>
												<td class="sh-sizes text-left">#@item.Deadline.ToString("dd/MM/yyyy")</td>
												<td class="sh-download">
													<div class="dropdown sub-title">
														<a class="sub btn btn-secondary" asp-action="Details" asp-route-id="@item.Id" title="Xem chi tiết">
															Xem chi tiết
														</a>
													</div>
												</td>
											</tr>
										}
									</tbody>
								</table>
								<div class="text-xs-right pageinate-page-blog section">
									@Html.PagedListPager(Model, page => Url.Action("Index", "Recruitments", new { page = page }))
								</div>
							</section>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="tab_blog">
		<div class="container">
			<div class="tab-ul">
				<ul class="tabs">
					<li class="nav-link active" data-tab="#tab-1">Gợi ý công việc phù hợp</li>
					<li class="nav-link" data-tab="#tab-2">Các công việc đã xem</li>
				</ul>
				<div class="tab-content active" id="tab-1">
					@if (hotRecruitment != null && hotRecruitment.Count > 0)
					{
						<div class="row">
							@foreach (var item in hotRecruitment)
							{
								<div class="col-lg-3 col-6">
									<a class="item" asp-controller="Recruitments" asp-action="Details" class="image-blog" asp-route-id="@item.Id" title="@item.Name">
										@item.Name
									</a>
								</div>
							}
						</div>
					}
				</div>
				<div class="tab-content" id="tab-2">
					<div class="row">
						<!-- sản phẩm đã xem -->
					</div>
				</div>
			</div>
		</div>
	</div>
	@if (enviromentNews != null && enviromentNews.Count > 0)
	{
		<div class="blog_moitruong">
			<div class="container">
				<div class="title">Môi trường làm việc </div>
				<div class="row">
					@foreach (var item in enviromentNews)
					{
						<div class="col-md-4 item item-1">
							<div class="img">
								<img src="@item.Image"
									 alt="@item.Title">
							</div>
							<div class="content">
								<div class="title"> @item.Title</div>
								<a asp-controller="News" asp-action="Details" class="image-blog" asp-route-id="@item.Id" title="@item.Title">
									TÌM HIỂU THÊM <i class="fas fa-arrow-right"></i>
								</a>
							</div>
						</div>
					}

				</div>
			</div>
		</div>
	}
</section>
<script type="text/javascript">
	jQuery(document).ready(function ($) {
		showViewedProducts();
	});
	function showViewedProducts() {
		// Lấy danh sách đã xem từ local storage
		let viewedProducts = JSON.parse(localStorage.getItem('viewedProducts')) || [];
		let productsContainer = $('#tab-2').find('.row');
		viewedProducts.forEach(product => {
			// Tạo phần tử div cho mỗi sản phẩm
			let productDiv = $('<div>').addClass('col-lg-3 col-6');
			let productLink = $('<a>').addClass('item').attr('href', '/Recruitments/Details/' + product.id);
			let productName = $('<p>').text(product.name);

			// Thêm phần tử vào phần tử chứa sản phẩm
			productLink.append(productName);
			productDiv.append(productLink);
			productsContainer.append(productDiv);
		});
		// Kiểm tra nếu có nhiều hơn 4 sản phẩm, xóa phần tử đầu tiên
		if (viewedProducts.length > 4) {
			productsContainer.find('.col-lg-3:first').remove();
		}
	}
</script>