TechMed/Areas/Admin/Models/Banner/Banner.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TechMed.Areas.Admin.Models.Banner
{
    [Table("Banner")]
    public class Banner
    {
        [Key]
        public Guid Id { get; set; }

        [StringLength(500, ErrorMessage = "Tên banner không quá 500 kí tự")]
        public string Name { get; set; } = "";

        public string? ImageUrl { get; set; }

        public int Status { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn ngày hiển thị.")]
        public DateTime StartDate { get; set; }

        public DateTime? EndDate { get; set; }

		public int? Order { get; set; }

		public string? Link { get; set; }

		[Required(ErrorMessage = "Vui lòng chọn vị trí banner hiển thị.")]
        public Guid BannerPositionId { get; set; }
        public BannerPosition? BannerPosition { get; set; }

    }
}

TechMed/Areas/Admin/Models/Banner/BannerPosition.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TechMed.Areas.Admin.Models.Banner
{
    [Table("BannerPosition")]
    public class BannerPosition
    {
        [Key]
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên vị trí.")]
        public string Name { get; set; } = "";

        [Required(ErrorMessage = "Vui lòng nhập mã vị trí.")]
        public string Code { get; set; } = "";

        public string? Description { get; set; }

        public List<Banner>? Banners { get; set; }
    }
}

TechMed/Areas/Admin/Controllers/BannersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TechMed.Areas.Admin.Data;
using TechMed.Areas.Admin.Models.Banner;
using X.PagedList;

namespace TechMed.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class BannersController : Controller
    {
        private readonly AppDbContext _context;

		public BannersController(AppDbContext context)
        {
            _context = context;
		}

        // GET: Admin/Banners
        public async Task<IActionResult> Index(int? page)
        {
            int pageSize = 10; //SL phan tu tren 1 trang
            int pageNumber = (page ?? 1);
			var banners = await _context.Banner
						  .Include(b => b.BannerPosition)
						  .ToListAsync();
            IPagedList<Banner> bannerPaging = banners.ToPagedList(pageNumber, pageSize);
            if (banners != null)
			{
				return View(bannerPaging);
			}
			else
			{
				// Nếu danh sách Banner là null, trả về thông báo lỗi
				return Problem("Entity set 'AppDbContext.Banner' is null.");
			}
		}

        [HttpPost]
		// GET: Admin/Banners
		public async Task<IActionResult> Index(string? keyword, int? page)
		{
			int pageSize = 10; //Số phần tử trên mỗi trang
			int pageNumber = page ?? 1;

			IQueryable<Banner> bannerQuery = _context.Banner.Include(b => b.BannerPosition);

			if (!string.IsNullOrEmpty(keyword))
			{
				bannerQuery = bannerQuery.Where(n => n.Name.Contains(keyword));
			}

			var banners = await bannerQuery.ToListAsync();
			IPagedList<Banner> bannerPaging = banners.ToPagedList(pageNumber, pageSize);

			ViewBag.keyword = keyword;

			if (banners != null)
			{
				return View(bannerPaging);
			}
			else
			{
				// Nếu danh sách Banner là null, trả về thông báo lỗi
				return Problem("Entity set 'AppDbContext.Banner' is null.");
			}
		}

		// GET: Admin/Banners/Details/5
		public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Banner == null)
            {
                return NotFound();
            }

            var banner = await _context.Banner
                .FirstOrDefaultAsync(m => m.Id == id);
            if (banner == null)
            {
                return NotFound();
            }

            return View(banner);
        }

        // GET: Admin/Banners/Create
        public IActionResult Create()
        {
            ViewData["BannerPositionId"] = new SelectList(_context.BannerPosition, "Id", "Name");
            return View();
        }

        // POST: Admin/Banners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Name,ImageUrl,Status,Order,Link,StartDate,EndDate,BannerPositionId")] Banner banner, IFormFile? ImageUrl)
        {
            if (ModelState.IsValid)
            {
                if (ImageUrl != null && ImageUrl.Length > 0)
                {
                    // Tạo tên tệp ảnh duy nhất
                    var uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageUrl.FileName;

					// Lưu ảnh vào thư mục của ứng dụng
                    var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Upload/banner", uniqueFileName);
                    using (var stream = new FileStream(imagePath, FileMode.Create))
                    {
                        await ImageUrl.CopyToAsync(stream);
                    }

                    banner.ImageUrl = Url.Content(Path.Combine("~/Upload/banner/", uniqueFileName));
                }
                banner.Id = Guid.NewGuid();
                _context.Add(banner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BannerPositionId"] = new SelectList(_context.BannerPosition, "Id", "Name",banner.BannerPositionId);
            return View(banner);
        }

        // GET: Admin/Banners/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Banner == null)
            {
                return NotFound();
            }

            var banner = await _context.Banner.FindAsync(id);
            if (banner == null)
            {
                return NotFound();
            }
            ViewData["BannerPositionId"] = new SelectList(_context.BannerPosition, "Id", "Name", banner.BannerPositionId);
            return View(banner);
        }

        // POST: Admin/Banners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, 
            [Bind("Id,Name,ImageUrl,Status,Order,Link,StartDate,EndDate,BannerPositionId")] Banner banner, IFormFile? ImageUrl, string? imgData)
        {
            if (id != banner.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (ImageUrl != null && ImageUrl.Length > 0)
                    {
						if (imgData != null)
						{
							DeleteBannerImage(imgData);
						}
						// Tạo tên tệp ảnh duy nhất
						var uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageUrl.FileName;

                        // Lưu ảnh vào thư mục của ứng dụng
                        var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Upload/banner", uniqueFileName);
                        using (var stream = new FileStream(imagePath, FileMode.Create))
                        {
                            await ImageUrl.CopyToAsync(stream);
                        }

                        banner.ImageUrl = Url.Content(Path.Combine("~/Upload/banner/", uniqueFileName));
                    }
                    else
                    {
                        banner.ImageUrl = imgData;

					}
                    _context.Update(banner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BannerExists(banner.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BannerPositionId"] = new SelectList(_context.BannerPosition, "Id", "Name", banner.BannerPositionId);
            return View(banner);
        }

        // GET: Admin/Banners/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Banner == null)
            {
                return NotFound();
            }

            var banner = await _context.Banner
                .FirstOrDefaultAsync(m => m.Id == id);
            if (banner == null)
            {
                return NotFound();
            }

            return View(banner);
        }

        // POST: Admin/Banners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
            {
            if (_context.Banner == null)
            {
                return Problem("Dữ liệu không tồn tại");
            }
            var banner = await _context.Banner.FindAsync(id);
            if (banner != null)
            {
				_context.Banner.Remove(banner);
                if (banner.ImageUrl != null)
                {
                    DeleteBannerImage(banner.ImageUrl);
				}
			}
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BannerExists(Guid id)
        {
          return (_context.Banner?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        //Hàm xóa ảnh
        private void DeleteBannerImage(string bannerUrl)
        {
			var imagePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Upload/banner", bannerUrl.Replace("/Upload/banner/", ""));
			// Kiểm tra xem tệp ảnh tồn tại không
			if (System.IO.File.Exists(imagePath))
			{
				// Nếu tệp ảnh tồn tại, xóa nó khỏi thư mục
				System.IO.File.Delete(imagePath);
			}
		}
    }
}

TechMed/Areas/Admin/Views/Banners/Create.cshtml
@model TechMed.Areas.Admin.Models.Banner.Banner

@{
	ViewData["Title"] = "Create";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Tạo mới</h1>

<h4>Banner</h4>
<hr />

<form asp-action="Create" enctype="multipart/form-data">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="row">
		<div class="col-12 col-md-6">
			<div class="form-group">
				<label asp-for="Name" class="control-label"></label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ImageUrl" class="control-label"></label>
				<input type="file" name="ImageUrl" class="form-control" accept="image/*"/>
				<span asp-validation-for="ImageUrl" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Status" class="control-label">Trạng thái</label>
				<select asp-for="Status" class="form-control">
					<option value="1">Hoạt động</option>
					<option value="0">Không hoạt động</option>
				</select>
				<span asp-validation-for="Status" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Link" class="control-label"></label>
				<input asp-for="Link" class="form-control" />
				<span asp-validation-for="Link" class="text-danger"></span>
			</div>
		</div>
		<div class="col-12 col-md-6">
			<div class="form-group">
				<label asp-for="StartDate" class="control-label"></label>
				<input asp-for="StartDate" class="form-control" />
				<span asp-validation-for="StartDate" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="EndDate" class="control-label"></label>
				<input asp-for="EndDate" class="form-control" />
				<span asp-validation-for="EndDate" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BannerPositionId" class="control-label"></label>
				<select asp-for="BannerPositionId" class="form-control" asp-items="ViewBag.BannerPositionId"></select>
				<span asp-validation-for="BannerPositionId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Order" class="control-label"></label>
				<input asp-for="Order" class="form-control" />
				<span asp-validation-for="Order" class="text-danger"></span>
			</div>
		</div>
	</div>
	<div class="form-group">
		<input type="submit" value="Create" class="btn btn-primary" />
	</div>
</form>


<div>
	<a asp-action="Index">Back to List</a>
</div>

TechMed/Areas/Admin/Views/Banners/Delete.cshtml
@model TechMed.Areas.Admin.Models.Banner.Banner

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Banner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BannerPositionId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BannerPositionId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TechMed/Areas/Admin/Views/Banners/Details.cshtml
@model TechMed.Areas.Admin.Models.Banner.Banner

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Banner</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            <img style="width:50px;height:50px" src="~/Upload/banner/@Html.DisplayFor(model => model.ImageUrl)">
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BannerPositionId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BannerPositionId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TechMed/Areas/Admin/Views/Banners/Edit.cshtml
@model TechMed.Areas.Admin.Models.Banner.Banner

@{
	ViewData["Title"] = "Edit";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Chỉnh sửa</h1>

<h4>Banner</h4>
<hr />
<form asp-action="Edit" enctype="multipart/form-data">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<input type="hidden" asp-for="Id" />
	<div class="row">
		<div class="col-12 col-md-6">
			<div class="form-group">
				<label asp-for="Name" class="control-label">Tên banner</label>
				<input asp-for="Name" class="form-control" />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ImageUrl" class="control-label">Ảnh</label>
				<div class="d-flex">
					<input type="file" name="ImageUrl" class="form-control" accept="image/*" />
					<img src="@Model.ImageUrl" id="imgData" name="imgData" style="max-width:30px;max-height:30px" />
				</div>
				<span asp-validation-for="ImageUrl" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Status" class="control-label">Trạng thái</label>
				<select asp-for="Status" class="form-control">
					<option value="1">Hoạt động</option>
					<option value="0">Không hoạt động</option>
				</select>
				<span asp-validation-for="Status" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Link" class="control-label">Link dẫn</label>
				<input asp-for="Link" class="form-control" />
				<span asp-validation-for="Link" class="text-danger"></span>
			</div>
		</div>
		<div class="col-12 col-md-6">
			<div class="form-group">
				<label asp-for="StartDate" class="control-label">Ngày bắt đầu</label>
				<input asp-for="StartDate" class="form-control" />
				<span asp-validation-for="StartDate" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="EndDate" class="control-label">Ngày kết thúc</label>
				<input asp-for="EndDate" class="form-control" />
				<span asp-validation-for="EndDate" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="BannerPositionId" class="control-label">Vị trí banner</label>
				<select asp-for="BannerPositionId" class="form-control" asp-items="ViewBag.BannerPositionId"></select>
				<span asp-validation-for="BannerPositionId" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Order" class="control-label">Sắp xếp</label>
				<input asp-for="Order" class="form-control" />
				<span asp-validation-for="Order" class="text-danger"></span>
			</div>
		</div>
	</div>
	<div class="form-group">
		<input type="submit" value="Save" class="btn btn-primary" />
	</div>
</form>
<script>
	$(document).ready(function () {
		$('form[method="post"]').submit(function () {
			// Lấy giá trị của trường imgData
			var imgData = $('#imgData').attr('src');
			if (imgData) {
				// Thêm giá trị imgData vào một input hidden trong form
				$('<input>').attr({
					type: 'hidden',
					name: 'imgData',
					value: imgData
				}).appendTo('form');
			}

			// Không cần xử lý bất kỳ thứ gì khác, chỉ cần submit form
			return true;
		});
	});
</script>

TechMed/Areas/Admin/Views/Banners/Index.cshtml
@model X.PagedList.IPagedList<TechMed.Areas.Admin.Models.Banner.Banner>
@using X.PagedList.Mvc.Core

@{
	ViewData["Title"] = "Danh sách banner";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Danh sách banner</h1>

<div class="searchInner">
	<form method="post">
		<div class="row">
			<div class="searchField col-md-4 col-6">
				<input class="form-control" type="text" name="keyword" value="@ViewBag.keyword" placeholder="Search content here..." />
			</div>

			<div class="btnFilter col-md col-12">
				<input type="submit" value="Tìm kiếm" class="btn" />
			</div>
		</div>
	</form>
</div>

<div class="d-flex justify-content-between align-items-center button-header">

	<a class="btn btn-success btnCreateNew" asp-action="Create">Tạo mới</a>

	@Html.PagedListPager(Model, page => Url.Action("Index", "Banners", new { page = page }))
</div>

<table class="table">
	<thead>
		<tr>
			<th>
				Tên
			</th>
			<th>
				Ảnh
			</th>
			<th>
				Trạng thái
			</th>
			<th>
				Ngày bắt đầu
			</th>
			<th>
				Ngày kết thúc
			</th>
			<th>
				Vị trí banner
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Name)
				</td>
				<td>
					<img style="width:50px;height:50px" src="@item.ImageUrl">
					@* @Html.DisplayFor(modelItem => item.ImageUrl) *@
				</td>
				<td>
					<div class="d-flex align-items-center">
						@if (item.Status == 1)
						{
							<div class="status-dot status-active"></div>
							<span>Active</span>
						}
						else if (item.Status == 0)
						{
							<div class="status-dot status-warning"></div> <span>Inactive</span>
						}
						else
						{
							<span>Unknown status</span>
						}
					</div>
				</td>
				<td>
					@(item.StartDate != null ? item.StartDate.ToString("dd/MM/yyyy hh:mm:ss") : "N/A")
				</td>
				<td>
					@(item.EndDate != null ? item.EndDate?.ToString("dd/MM/yyyy hh:mm:ss") : "N/A")
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.BannerPosition.Name)
				</td>
				<td>
					<div class="dropdown">
						<a class="dropdown-toggle" href="#" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
							<i class="fa-solid fa-bars text-secondary"></i>
						</a>

						<ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
							<li><a class="dropdown-item" asp-action="Edit" asp-route-id="@item.Id"><i class="fa-solid fa-pencil"></i> Sửa</a></li>
							<li data-bs-toggle="modal" data-bs-target="#deleteModal" data-id="@item.Id" class="btnDelete">
								<a href="javascript:void(0)" class="dropdown-item"><i class="fa-solid fa-trash-can text-danger"></i> Xóa</a>
							</li>
						</ul>
					</div>
				</td>
			</tr>
		}
	</tbody>
</table>
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Xác nhận xóa ?</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="alert alert-warning" role="alert">
					Bạn có chắc chắn muốn xóa: Banner
				</div>
			</div>
			<div class="modal-footer">
				<form asp-action="Delete">
					<input type="hidden" name="Id" class="idElement" />
					<input type="submit" value="Xóa" class="btn btn-danger" />
					<input type="button" value="không" class="btn btn-secondary" data-bs-dismiss="modal"/>
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).on("click", ".btnDelete", function () {
		var itemId = $(this).data('id');
		$(".modal-footer .idElement").val(itemId);
	});
</script>